runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static
  application_readable: true

- url: .*
  script: main.app

# [END handlers]